export const trendingItems = [
    {
        id: 1,
        img: 'images/trending/adicolor-FW21-Oct-HP-M-Teaser-Carousel-1-D-M-T_fkvja7.jpg',
        title: 'Higher comfort with Supernova',
        des: 'Define your ritual and burn more miles. Available in a new colourway.',
    },
    {
        id: 2,
        img: 'images/trending/adicolor-FW21-Sept-HP-Teaser-Carousel-3_qvx5fb.jpg',
        title: 'ONCE A SUPERSTAR, ALWAYS A SUPERSTAR.',
        des: 'Một thiết kế biểu tượng từ năm 1970, đây là di sản giày sneaker.',
    },
    {
        id: 3,
        img: 'images/trending/football-fw21-manunited-home-hp-tc-1_tcm337-707619.jpg',
        title: 'FUTURECRAFT 4D',
        des: 'Định hình tương lai của thể thao.',
    },
    {
        id: 4,
        img: 'images/trending/fw21-lego_week-launch-hp-teaser-carousel-d_tcm337-763557.jpg',
        title: 'CHẠY BỘ VỚI GIÀY SUPERNOVA',
        des: 'Năng lượng kết hợp sự thoải mái. Đã mở bán.',
    },
    {
        id: 5,
        img: 'images/trending/ozworld-teaser_tcm337-754786.jpg',
        title: 'TRAIN TO CHILL',
        des: 'Raising your BPM or bringing it down. Exclusive drops only available at adidas have you covered.',
    },
    {
        id: 6,
        img: 'images/trending/running-fw21-adizero-september-launch-hp-teaser-carousel-gender-neutral-fallback-d_tcm337-720076.jpg',
        title: '',
        des: '',
    },
    {
        id: 7,
        img: 'images/trending/running-fw21-futurecraft-4d-launch-hp-teaser-carousel-d_tcm337-730369.jpg',
        title: 'FEEL THE ZX',
        des: 'Thân giày cá tính ôm trọn bàn chân bạn với nhiều lớp chất liệu đậm chất tương lai. Cảm nhận sự thoải mái.',
    },
    {
        id: 8,
        img: 'images/trending/running-ss22-supernova-launch-glp-m-teaser-carousel-d_tcm337-825366.jpg',
        title: 'SOME SHOES, SOME YEAR',
        des: 'With the help of the adizero, our athletes ran the records in 2021.',
    },
    {
        id: 9,
        img: 'images/trending/superstar-hp-teaser_tcm337-760318.jpg',
        title: 'HU NMD BBC',
        des: 'Giày chạy đường dài',
    },
]

export const shoesItems = [
    {
        id: 1,
        img: 'images/shoes/FORUM_LOW_trang_GY5835_01_standard.png',
        price: '2.500.000đ',
        title: 'Supperstar',
        des: 'Nam originals',
        status: 'mới',
    },
    {
        id: 2,
        img: 'images/shoes/FORUM_LOW_W_Hong_GW0569_01_standard.jpg',
        price: '4.800.000đ',
        title: 'Giày Forum Premiere',
        des: 'Nam originals',
        status: 'mới',
    },{
        id: 3,
        img: 'images/shoes/Giay_Forum_Luxe_Low_trang_GX0516_01_standard.jpg',
        price: '3.000.000đ',
        title: 'Giày Forum Luxe Low',
        des: 'Nam originals',
        status: 'mới',
    },{
        id: 4,
        img: 'images/shoes/Giay_Forum_Luxe_Low_trang_GY5711_01_standard.jpg',
        price: '3.000.000đ',
        title: 'Giày Forum Luxe Low',
        des: 'Nữ originals',
        status: 'mới',
    },{
        id: 5,
        img: 'images/shoes/Giay_Forum_Luxe_Mid_trang_GX0519_01_standard.jpg',
        price: '3.400.000đ',
        title: 'Xbox forum tech boost',
        des: 'Nam originals',
        status: 'mới',
    },{
        id: 6,
        img: 'images/shoes/Giay_Forum_Premiere_DJen_GY5799_01_standard.jpg',
        price: '3.000.000đ',
        title: 'Giày Supperstar',
        des: 'Nam originals',
        status: 'mới',
    },{
        id: 7,
        img: 'images/shoes/Giay_OZWEEGO_trang_GX8878_01_standard.png',
        price: '3.500.000đ',
        title: 'Giày Ozweego',
        des: 'Nam originals',
        status: 'mới',
    },{
        id: 8,
        img: 'images/shoes/Giay_Superstar_trang_GX8839_01_standard.jpg',
        price: '3.500.000đ',
        title: 'Giày forum luxe mid',
        des: 'Nam originals',
        status: 'mới',
    },{
        id: 9,
        img: 'images/shoes/SUPERSTAR_trang_FZ1968_01_standard.jpg',
        price: '3.000.000đ',
        title: 'Supperstar w',
        des: 'Nữ originals',
        status: 'mới',
    },{
        id: 10,
        img: 'images/shoes/SUPERSTAR_W_trang_GW0570_01_standard.jpg',
        price: '2.500.000đ',
        title: 'Forum low',
        des: 'Nam originals',
        status: 'mới',
    },{
        id: 11,
        img: 'images/shoes/XBOX_FORUM_TECH_BOOST_DJen_GW6374_01_standard.jpg',
        price: '2.500.000đ',
        title: 'Forum low w',
        des: 'Nữ originals',
        status: 'mới',
    },
]