export const interested = [
    {
        id: 1,
        img: 'images/interested/Ba_Lo_FA_Classic_DJen_H31339_01_standard.jpg',
        price: '1.200.000đ',
        title: 'Classic FA Backpack',
        des: 'Performance',
    },
    {
        id: 2,
        img: 'images/interested/Ba_lo_Power_5_trai_cam_H45603_01_standard.jpg',
        price: '950.000đ',
        title: 'Power 5 Backpack',
        des: 'Performance',
    },
    {
        id: 3,
        img: 'images/interested/Mu_Snapback_Tour_DJen_H57155_01_standard.jpg',
        price: '650.000đ',
        title: 'Tour Snapback Hat',
        des: 'Performance',
    },
    {
        id: 4,
        img: 'images/interested/Tui_DJa_Nang_Dang_Ngang_Classic_DJen_H30332_01_standard.jpg',
        price: '400.000đ',
        title: 'Classic Essential Waist Bag',
        des: 'Performance',
    },
    {
        id: 5,
        img: 'images/interested/Tui_DJa_Nang_Vien_BTS_DJen_HE2678_01_standard.jpg',
        price: '650.000đ',
        title: 'BTS Piping Organizer',
        des: 'Performance',
    },
    {
        id: 6,
        img: 'images/interested/Tui_DJeo_Hong_Camo_Xam_H34639_01_standard.jpg',
        price: '650.000đ',
        title: 'Camo Waist Bag',
        des: 'Performance',
    },
    {
        id: 7,
        img: 'images/interested/Tui_DJeo_Hong_Essential_Classic_DJen_H30343_01_standard.jpg',
        price: '400.000đ',
        title: 'Classic Essential Waist Bag',
        des: 'Performance',
    },
    {
        id: 8,
        img: 'images/interested/Tui_DJeo_Hong_Symbol_DJen_H34646_01_standard.jpg',
        price: '950.000đ',
        title: 'Symbol Waist Bag',
        des: 'Originals',
    },
    {
        id: 9,
        img: 'images/interested/Tui_Festival_Camo_Xam_H34628_01_standard.jpg',
        price: '1.200.000đ',
        title: 'Camo Festival Bag',
        des: 'Originals',
    },
    {
        id: 10,
        img: 'images/interested/Tui_Festival_Classic_Adicolor_DJen_HD7162_01_standard.jpg',
        price: '500.000đ',
        title: 'Adicolor Classic Festival Bag',
        des: 'Originals',
    },
    {
        id: 11,
        img: 'images/interested/Tui_Tote_Ti_Hon_DJen_HC7220_01_standard.jpg',
        price: '300.000đ',
        title: 'Tiny Tote',
        des: 'Performance',
    },
    {
        id: 12,
        img: 'images/interested/W_FI_MARIM_UN_B_DJen_GU0992_01_standard.jpg',
        price: '1.200.000đ',
        title: 'W FI MARIM UN B',
        des: 'Performance',
    },
]
export const trendingItems = [
    {
        id: 1,
        img: 'images/trending/8976-teasercarousel_tcm337-806039.jpg',
        title: 'Superturf adventure X atmos',
        des: 'Available now',
    },
    {
        id: 2,
        img: 'images/trending/adicolor-FW21-Oct-HP-M-Teaser-Carousel-1-D-M-T_fkvja7.jpg',
        title: 'BOLDLY ADICOLOR',
        des: 'Phiên bản cải tiến cá tính từ adidas kinh điển.',
    },
    {
        id: 3,
        img: 'images/trending/fw21-holiday-originals-krusty-burger-teasercard_tcm337-818983.jpg',
        title: 'BACK FOR SECONDS',
        des: 'What a treat. The ZX 10000 Krusty Burger is back on the menu.',
    },
    {
        id: 4,
        img: 'images/trending/fw21-lego_week-launch-hp-teaser-carousel-d_tcm337-763557.jpg',
        title: 'ADIDAS x LEGO® WEEK',
        des: 'A shared passion for creativity—signature shapes of LEGO® products combine with classic styles of adidas.',
    },
    {
        id: 5,
        img: 'images/trending/fw21-pw-hu_nmd-bbc-drop2-tcc-d_tcm337-822376.jpg',
        title: 'HU NMD BBC',
        des: 'Nét thẩm mỹ đặc trưng của Pharrell đưa logo ấn tượng của BBC lên kiểu dáng giày đặc trưng của anh. Sắp ra mắt.',
    },
    {
        id: 6,
        img: 'images/trending/fw21-pw-hu_nmd-bbc-tcc_tcm337-796101.jpg',
        title: 'HU NMD BBC',
        des: "As a nod to Billionaire Boys Club, Pharrell's signature silhouette features BBC's iconic logo. Out now.",
    },
    {
        id: 7,
        img: 'images/trending/ozworld-teaser_tcm337-754786.jpg',
        title: 'Welcome to Ozworld',
        des: 'A multi-dimensional reality where your next life begins every time you want it.',
    },
    {
        id: 8,
        img: 'images/trending/running-fw21-futurecraft-4d-launch-hp-teaser-carousel-d_tcm337-730369.jpg',
        title: 'FUTURECRAFT 4D',
        des: 'Định hình tương lai của thể thao.',
    },
    {
        id: 9,
        img: 'images/trending/running-ss22-adistar-december-catlp-teaser-carousel-d_tcm337-799604.jpg',
        title: 'SUPPORTIVE',
        des: 'Giày chạy đường dài',
    },
    {
        id: 10,
        img: 'images/trending/super-tcc_tcm337-784863.jpg',
        title: 'Higher comfort with Supernova',
        des: 'Define your ritual and burn more miles. Available in a new colourway.',
    },
    {
        id: 11,
        img: 'images/trending/superstar-hp-teaser_tcm337-760318.jpg',
        title: 'ONCE A SUPERSTAR, ALWAYS A SUPERSTAR.',
        des: 'Một thiết kế biểu tượng từ năm 1970, đây là di sản giày sneaker.',
    },
    {
        id: 12,
        img: 'images/trending/triple-black-tesaer_tcm337-784836.jpg',
        title: 'THE TRIPLE BLACK COLLECTION',
        des: 'Sneakers to wear with everything.',
    },
]

export const shoesItems = [
    {
        id: 1,
        img: 'images/shoes/FORUM_LOW_trang_GY5835_01_standard.png',
        price: '2.500.000đ',
        title: 'Supperstar',
        des: 'Nam originals',
        status: 'mới',
    },
    {
        id: 2,
        img: 'images/shoes/FORUM_LOW_W_Hong_GW0569_01_standard.jpg',
        price: '4.800.000đ',
        title: 'Giày Forum Premiere',
        des: 'Nam originals',
        status: 'mới',
    },{
        id: 3,
        img: 'images/shoes/Giay_Forum_Luxe_Low_trang_GX0516_01_standard.jpg',
        price: '3.000.000đ',
        title: 'Giày Forum Luxe Low',
        des: 'Nam originals',
        status: 'mới',
    },{
        id: 4,
        img: 'images/shoes/Giay_Forum_Luxe_Low_trang_GY5711_01_standard.jpg',
        price: '3.000.000đ',
        title: 'Giày Forum Luxe Low',
        des: 'Nữ originals',
        status: 'mới',
    },{
        id: 5,
        img: 'images/shoes/Giay_Forum_Luxe_Mid_trang_GX0519_01_standard.jpg',
        price: '3.400.000đ',
        title: 'Xbox forum tech boost',
        des: 'Nam originals',
        status: 'mới',
    },{
        id: 6,
        img: 'images/shoes/Giay_Forum_Premiere_DJen_GY5799_01_standard.jpg',
        price: '3.000.000đ',
        title: 'Giày Supperstar',
        des: 'Nam originals',
        status: 'mới',
    },{
        id: 7,
        img: 'images/shoes/Giay_OZWEEGO_trang_GX8878_01_standard.png',
        price: '3.500.000đ',
        title: 'Giày Ozweego',
        des: 'Nam originals',
        status: 'mới',
    },{
        id: 8,
        img: 'images/shoes/Giay_Superstar_trang_GX8839_01_standard.jpg',
        price: '3.500.000đ',
        title: 'Giày forum luxe mid',
        des: 'Nam originals',
        status: 'mới',
    },{
        id: 9,
        img: 'images/shoes/SUPERSTAR_trang_FZ1968_01_standard.jpg',
        price: '3.000.000đ',
        title: 'Supperstar w',
        des: 'Nữ originals',
        status: 'mới',
    },{
        id: 10,
        img: 'images/shoes/SUPERSTAR_W_trang_GW0570_01_standard.jpg',
        price: '2.500.000đ',
        title: 'Forum low',
        des: 'Nam originals',
        status: 'mới',
    },{
        id: 11,
        img: 'images/shoes/XBOX_FORUM_TECH_BOOST_DJen_GW6374_01_standard.jpg',
        price: '2.500.000đ',
        title: 'Forum low w',
        des: 'Nữ originals',
        status: 'mới',
    },
]